backend:
  name: git-gateway
  branch: main-01

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

media_folder: "src/assets/images/cms"
public_folder: "/assets/images/cms"

collections:
  - name: "cms"
    label: "cms"
    folder: "src/content/cms"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }

